# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Shloka Negi - Portfolio
author: Shloka Negi
email: shnegi@ucsc.edu
description: Portfolio of Shloka Negi, a 3rd year Bioinformatics PhD student at UCSC.
url: 'https://shlokanegi.github.io'
baseurl: ''

# Custom variables
github_username: shlokanegi
linkedin_username: shloka-negi
googlescholar_id: BsF9-KsAAAAJ&hl=en
orcid_id: 0000-0002-9839-4030

# Build settings
markdown: kramdown
kramdown:
  input: GFM

theme: minima # Assuming you want to keep a theme, minima is common. You can change this.

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Defaults
defaults:
  - scope:
      path: "" # all files
      type: "pages" # limit to pages
    values:
      layout: "default"
  - scope:
      path: "" # all files
      type: "projects" # limit to items in the 'projects' collection
    values:
      layout: "project_item"

# Sass settings
sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Navigation settings for single-page scroll
navigation_links:
  - { title: "Home", section_id: "home" }
  - { title: "Projects", section_id: "projects" }
  - { title: "Publications", section_id: "publications" }
  - { title: "Talks", section_id: "talks" }
  - { title: "Contact", section_id: "contact" }
